### ISSUE TITLE
Installing issues.

### ISSUE THREAD

**Issue by shmink** [Nattfodd/dji_parser#3]
New to Ruby and I'm afraid the installing process doesn't make much sense. Without effecting the Gemfile and just using the command `gem install dji_parser` I get the following output.

`ERROR:  Could not find a valid gem 'dji_parser' (>= 0) in any repository`
`ERROR:  Possible alternatives: ddi-parser, bai_parser, cli-parser, ddl_parser, docparser
`

Then trying with editing the Gemfile by adding `gem 'dji_parser'` and bundling in the same directory (which is what you seemed to imply from your README, I then get this different output:

`fatal: Not a git repository (or any of the parent directories): .git`
`Your Gemfile lists the gem dji_parser (>= 0) more than once.`
`You should probably keep only one of them.`
`While it's not a problem now, it could cause errors if you change the version of just one of them later.`

`[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.`
`You specified that dji_parser (>= 0) should come from source at `.` and 
. Bundler cannot continue.`

 `#  from /home/tom/Desktop/dji_parser-master/dji_parser-master/Gemfile:5`
 `#  -------------------------------------------`
` #  gemspec`
` >  gem 'dji_parser'`
` #  -------------------------------------------`

Any help would be appreciated. I'm running Ubuntu 16.04 with ruby 2.3.1.

**Comment by nattfodd** [comment]
It's not published on rubygems, so you have to specify git path to the gem manually:

gem 'dji_parser', git: 'git@github.com:Nattfodd/dji_parser.git'

I don't maintain it atm, so it comes as it is

**Comment by shmink** [comment]
Sorry if I'm being dense but firstly do you mean that my entire Gemfile will look like the following?

`source 'https://rubygems.org'`

`# Specify your gem's dependencies in dji_parser.gemspec`
`# gemspec`
`gem 'dji_parser', git: 'git@github.com:Nattfodd/dji_parser.git'`

line `gemspec` is commented out because I at least seem to progress more. If this is the case then the next issue is that I am getting access right issues. Any ideas?

**Comment by shmink** [comment]
I think I have it installed now but I'm still unsure of how to actually use it. `ruby ./lib/dji_parser.rb` gives a `...cannot load such file...`. All the rake tests are correct and pass. And with `bundle exec rake install` I get an error saying that `FIXME or TODO is not a description`.

Have you tested this software with any of the relevant TXT files? Does the software work or is there any point pursuing this?
